### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by chkr1011** [FrankenApps/MqttDebugger#1]
Hi,

is it possible that you also create a binary package as zip for example when releasing a new version? In my opinion it would improve acceptance a lot.

Best regards
Christian

**Comment by FrankenApps** [comment]
Hi Christian,
thanks for your interest.
I do not quite understand the problem. I have a release containing binaries for all major desktop OSs [here](https://github.com/FrankenApps/MqttDebugger/releases/tag/0.1.0) (Currently not tested for Linux and MacOS though).

Do you mean you would like an unbundled version (e.g. containing the .exe and all dlls in a zip folder)?

Btw. I am using github actions for building new release versions (however currently only the repository owner can trigger new releases). You can look [here](https://github.com/FrankenApps/MqttDebugger/blob/0.1.0/.github/workflows/dotnet-core-publish.yml) in case you are interested in that.

**Comment by chkr1011** [comment]
Sorry I did not found the releases page 😄 

I am fine with that. Are you interested in some contributions in the future? I am looking for some alternative to MQTT Fx etc. with some more features.

**Comment by FrankenApps** [comment]
Well, I am definetly planning to add support for writing payloads to a folder and writing string data to a text file.
I will also need to improve the UI a bit and maybe compile the application using CoreRT. 
Once AvaloniaUI supports Android and iOS I will probably add support for these, too (but not publish the app to any stores).
Apart from that I am mostly fine with what the tool currently does for me (I basically needed only a way to send and receive Strings over the local network).
If you have some specific features in mind, feel free to propose them here...

**Comment by chkr1011** [comment]
OK thanks 😄
